#!/bin/bash

echo " =========================================================================="
echo "                       INPUT CONFIGURATION PARAMETERS                      "
echo " =========================================================================="
read -p "Enter VSM IP: " vsm_ip
read -p "Enter VSM username: " vsm_login
read -p "Enter VSM password: " vsm_pwd
echo " "
read -p "Enter tenant count: " tenant_count
read -p "Enter number of networks to be created per tenant: " per_tenant_seg_range_size
read -p "Enter network IP for first tenant network: " tenant_nw
read -p "Enter subnet prefix for first tenant network: " tenant_nw_prefix
read -p "Enter common password for all tenants and admin: " default_pwd
echo " "
read -p "Enter a common policy profile name for VMs: " vm_policy_profile
read -p "Enter physical network name: " phy_net
echo " "
read -p "Enter network IP for creating External Network: " ext_nw
read -p "Enter subnet prefix for External Network: " ext_nw_prefix
read -p "Enter VLAN for External Network: " ext_nw_vlan
echo " "
read -p "Enter the delay intended between each operation (In Secs): " pause
echo " "

echo "#!/bin/bash" > script_input
echo "admin_tenant=\"admin\"" >> script_input
echo "admin_uname=\"admin\"" >> script_input
echo "admin_pwd=\"$default_pwd\"" >> script_input
echo " " >> script_input
echo "vsm_ip=\"$vsm_ip\"" >> script_input
echo "vsm_login=\"$vsm_login\"" >> script_input
echo "vsm_pwd=\"$vsm_pwd\"" >> script_input
echo " " >> script_input
echo "tenant_count=\"$tenant_count\"" >> script_input
echo "per_tenant_seg_range_size=\"$per_tenant_seg_range_size\"" >> script_input
echo "tenant_nw=\"$tenant_nw\"" >> script_input
echo "tenant_nw_prefix=\"$tenant_nw_prefix\"" >> script_input
echo "default_pwd=\"$default_pwd\"" >> script_input
echo " " >> script_input
echo "vm_policy_profile=\"$vm_policy_profile\"" >> script_input
echo "phy_net=\"$phy_net\"" >> script_input
echo " " >> script_input
echo "ext_nw=\"$ext_nw\"" >> script_input
echo "ext_nw_prefix=\"$ext_nw_prefix\"" >> script_input
echo "ext_nw_vlan=\"$ext_nw_vlan\"" >> script_input
echo " " >> script_input
echo "pause=\"$pause\"" >> script_input
echo " "
echo " ================================================================================================"
echo " "
echo " A file 'script_input' is created successfully with above values."
echo " "
echo " Now go ahead and run ./cloud_admin.sh for Cloud Admin related operations and "
echo " run ./tenant_admin.sh for Tenant Admin related operations"
echo " "
echo " *Note: In multi-tenant execution, tenant network IP values  for multiple tenants will be" 
echo "   generated by incrementing second octet of the above given tenant network IP."
echo " "
echo " ================================================================================================="

