#!/bin/bash
admin_tenant="admin"
admin_uname="admin"
admin_pwd="e891d6cd0b9a002f26b5a4942f24d311"
 
vsm_ip="13.0.0.250"
vsm_login="admin"
vsm_pwd="Sfish123"
 
tenant_count="10"
per_tenant_seg_range_size="2"
tenant_nw="14.2.0.0"
tenant_nw_prefix="24"
default_pwd="e891d6cd0b9a002f26b5a4942f24d311"
 
vm_policy_profile="vm-pp"
phy_net="physnet-external"
 
ext_nw="15.2.0.0"
ext_nw_prefix="24"
ext_nw_vlan="900"
 
pause="2"
